name: Build, Test, and Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine pytest

      - name: Run tests with pytest
        run: pytest

      - name: Clean dist directory
        run: rm -rf dist/*

      - name: Build the wheel
        run: python setup.py bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
